# DeluxeCommands v1.7.0 Main configuration
# Created by extended_clip
# 
# Create commands below!
# Command format is as follows:
# 
# commands:
#   <command_with_no_slash>:
#     permission: <permission to use the command>
#     no_permission_message: <message to send when players do not have permission>
#     message:
#     - '[text]<regular text here if you start the line with the [text] identifier'
#     - '[playercommand] spawn'
#     - '[consolecommand] eco give %executor% 100'
#     - '{"text": "JSON text here"}'
#     - '{"text": "To have multiple JSON components in the same line"}&&{"text": "you must use the && operator between them!"}'
#     target_permission: <permission to use the command with a player argument at the end: /<command> (player)>
#     target_no_permission_message: <message to send when players do not have permission to specify a target to set placeholders for>
#     target_message:
#     - '[text]<You do not have to specify this option, only if you want separate messages when a target is defined>'
#     - '{"text": "%player%'s stats:"}'
#     - '{"text": "This message is only if you want a separate message defined when a"}&&{"text": " target player is specified in the command!"}'
#     aliases:
#     - 'somealiasforthiscommand'
# 
# You can now add a new entry to define different aliases per command!
#  simply add the "aliases" option to the commands you would like to define aliases for!
# DeluxeCommands will detect if you have DeluxeChat or PlaceholderAPI installed! You can use any placeholders you have enabled!
commands:
  classmage:
    permission: zpermission.default
    no_permission_message: '&cYou don''t have permission to use this command!'
    message:
    - '[playercommand] hg open hero-confirm'
    - '[playercommand] hero choose mage'

  ccon:
    permission: zpermission.default
    no_permission_message: '&cYou don''t have permission to use this command!'
    message:
    - '[playercommand] hero confirm'
    - '[playercommand] hg open main-page'
    
  ccan:
    permission: zpermission.default
    no_permission_message: '&cYou don''t have permission to use this command!'
    message:
    - '[playercommand] hero cancel'
    - '[playercommand] hg open main-page'